import type { AppSettings } from './types';

export const defaultSettings: AppSettings = {
  theme: 'dark',
  accentColor: 'purple',
  language: 'en',
  notifications: true,
  soundEnabled: true,
  fontSize: 'normal',
  compactMode: false,
  disappearingTTL: 'off',
};

export function cn(...classes: (string | boolean | undefined | null)[]): string {
  return classes.filter(Boolean).join(' ');
}

// Short, human-readable device label for the Sessions list, e.g. "Chrome · Windows 11".
export function getDeviceName(ua: string = navigator.userAgent): string {
  const lower = ua.toLowerCase();
  let browser = 'Web';
  if (/edg\//.test(lower)) browser = 'Edge';
  else if (/opr\/|opera/.test(lower)) browser = 'Opera';
  else if (/chrome\//.test(lower) && !/chromium/.test(lower)) browser = 'Chrome';
  else if (/chromium/.test(lower)) browser = 'Chromium';
  else if (/firefox\//.test(lower)) browser = 'Firefox';
  else if (/safari\//.test(lower)) browser = 'Safari';

  let os = 'Desktop';
  if (/iphone|ipad|ipod/.test(lower)) os = 'iPhone/iPad';
  else if (/windows nt 10/.test(lower)) os = 'Windows 10/11';
  else if (/windows nt 6\.[1-3]/.test(lower)) os = 'Windows';
  else if (/android/.test(lower)) os = 'Android';
  else if (/mac os x|macintosh/.test(lower)) os = 'macOS';
  else if (/linux/.test(lower)) os = 'Linux';

  return `${browser} · ${os}`;
}

export function formatTime(timestamp: number): string {
  const date = new Date(timestamp);
  const now = new Date();
  if (date.toDateString() === now.toDateString()) {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }
  if (date.getFullYear() === now.getFullYear()) {
    return date.toLocaleDateString([], { month: 'short', day: 'numeric' }) +
           ' ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }
  return date.toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' });
}

export function getAvatarText(nickname: string): string {
  const words = nickname.split(/[_\-\s]+/).filter(Boolean);
  if (words.length >= 2) {
    return (words[0][0] + words[1][0]).toUpperCase();
  }
  return nickname.charAt(0).toUpperCase();
}

const AVATAR_GRADIENTS = [
  'linear-gradient(135deg, #7c3aed, #a78bfa)',
  'linear-gradient(135deg, #2563eb, #60a5fa)',
  'linear-gradient(135deg, #059669, #34d399)',
  'linear-gradient(135deg, #dc2626, #f87171)',
  'linear-gradient(135deg, #ea580c, #fb923c)',
  'linear-gradient(135deg, #db2777, #f472b6)',
  'linear-gradient(135deg, #0d9488, #2dd4bf)',
  'linear-gradient(135deg, #4f46e5, #818cf8)',
  'linear-gradient(135deg, #d97706, #fbbf24)',
  'linear-gradient(135deg, #0284c7, #38bdf8)',
];

export function getAvatarGradient(nickname: string): string {
  let hash = 5381;
  for (let i = 0; i < nickname.length; i++) {
    hash = ((hash << 5) + hash + nickname.charCodeAt(i)) | 0;
  }
  return AVATAR_GRADIENTS[Math.abs(hash) % AVATAR_GRADIENTS.length];
}

export function loadSettings(): AppSettings {
  try {
    const saved = localStorage.getItem('wn_settings');
    if (saved) return { ...defaultSettings, ...JSON.parse(saved) };
  } catch {}
  return defaultSettings;
}

export const translations = {
  en: {
    connected: 'Online',
    connecting: 'Connecting...',
    disconnected: 'Offline',
    reconnecting: 'Reconnecting...',
    status_connected: 'Connected',
    status_disconnected: 'No connection',
    server_unreachable: 'Server is unreachable. Check your connection.',
    retry: 'Retry',
    status_connecting: 'Connecting...',
    settings: 'Settings',
    appearance: 'Appearance',
    general: 'Global Chat',
    theme: 'Theme',
    theme_dark: 'Dark',
    theme_light: 'Light',
    language: 'Language',
    lang_en: 'English',
    lang_ru: 'Русский',
    notifications: 'Notifications',
    enable_notifications: 'Enable notifications',
    sound: 'Sound',
    message_sound: 'Message sound',
    data: 'Data',
    clear_local_data: 'Clear local data',
    confirm_clear: 'Clear',
    confirm_clear_data: 'Clear all local data?',
    confirm_clear_data_desc: 'All settings and encryption keys will be removed from this browser. This action is irreversible.',
    cancel: 'Cancel',
    done: 'Done',
    copy: 'Copy',
    login: 'Login',
    register: 'Register',
    nickname: 'Nickname',
    password: 'Password',
    nickname_placeholder: 'Enter nickname (3-16 chars)',
    password_create: 'Create password (8-32 chars, letters + numbers)',
    password_enter: 'Enter password',
    create_account: 'Create Account',
    sign_in: 'Sign In',
    creating_account: 'Creating account...',
    signing_in: 'Signing in...',
    nickname_hint: 'Nickname: 3-16 chars, letters/numbers/_- only',
    type_message: 'Type a message...',
    not_connected: 'Not connected',
    send_message: 'Send message',
    close_settings: 'Close settings',
    logout: 'Log out',
    confirm_logout: 'Log out of account?',
    confirm_logout_desc: 'You will need to sign in again to continue using the messenger.',
    online_users: 'Online',
    no_messages: 'No messages yet. Say hello!',
    no_dm_messages: 'No messages yet. Say hi!',
    delete: 'Delete',
    search_messages: 'Search messages',
    search_messages_hint: 'Search in chat...',
    font_size: 'Font size',
    font_small: 'Small',
    font_normal: 'Normal',
    font_large: 'Large',
    compact_mode: 'Compact mode',
    enable_compact: 'Smaller gaps and padding',
    about: 'About',
    version: 'Version',
    contacts: 'Contacts',
    chat: 'Chat',
    back_to_chat: 'Back to chat',
    dm_with: 'Messages with',
    no_contacts: 'No conversations yet',
    start_dm: 'Send a message',
    search_placeholder: 'Search users...',
    search_results: 'Results',
    no_results: 'No users found',
    chats: 'Chats',
    global_chat: 'Global Chat',
    global_chat_desc: 'Public chat for everyone',
    home: 'Home',
    about_desc: 'Minimalist messenger with end-to-end encryption. Private, self-hosted, lightweight and fast. Your data stays on your server.',
    online: 'Online',
    offline: 'Offline',
    sec_appearance: 'Appearance',
    sec_text: 'Text',
    sec_notifications: 'Notifications',
    sec_account: 'Account',
    sec_safety: 'Security',
    safety_number: 'Safety Number',
    safety_number_desc: 'Compare this number with your contact to verify identity',
    safety_yours: 'Your safety number',
    export_keys: 'Export Keys',
    export_keys_desc: 'Download encrypted backup of your keys',
    import_keys: 'Import Keys',
    import_keys_desc: 'Restore keys from backup file',
    screenshot_prot: 'Screenshot Protection',
    screenshot_prot_desc: 'Block screen capture of this app',
    sessions: 'Active Sessions',
    sessions_desc: 'Manage connected devices',
    sessions_note: 'Up to 3 active sessions. Logging in from a new device while at the limit is rejected until you revoke an older session.',
    current_session: 'This device',
    editing_message: 'Editing message',
    admin_section: 'Moderation',
    admin_reports: 'Reports',
    admin_no_reports: 'No reports yet',
    admin_ban: 'Ban',
    admin_unban: 'Unban',
    admin_ban_nick: 'Ban by nickname',
    admin_ban_hint: '@nickname',
    admin_confirm_ban: 'Ban this user?',
    admin_confirm_unban: 'Unban this user?',
    admin_blocked: 'Blocked users',
    admin_blocked_empty: 'No one is banned',
    admin_unblock: 'Unblock',
    admin_channel_general: 'General chat',
    admin_channel_dm: 'DM',
    blocked_users: 'Blocked Users',
    blocked_hint: '@nickname to block',
    block: 'Block',
    block_confirm: 'Block this user? They will not be able to message you.',
    block_dialog_title: 'Block user',
    block_dialog_desc: 'Block this user? They will no longer be able to send you messages.',
    blocked_chat_hint: 'Blocked. Send messages after unblocking',
    unblock: 'Unblock',
    reply: 'Reply',
    edit_message: 'Edit',
    report: 'Report',
    report_title: 'Report user',
    report_desc: 'Tell us what this user did — a moderator will review it.',
    report_reason_scam: 'Scam',
    report_reason_harassment: 'Harassment',
    report_reason_inappropriate: 'Inappropriate content',
    report_reason_other: 'Other',
    report_send: 'Send report',
    report_sent: 'Report sent. Thank you for helping keep WhisperNet safe.',
    report_hint: 'Briefly describe the issue (optional)',
    revoke: 'Revoke',
    revoke_all: 'Revoke All Others',
    key_exported: 'Backup downloaded',
    key_imported: 'Keys restored from backup',
    key_import_err: 'Invalid backup file or wrong password',
    session_revoked: 'Session revoked',
    key_setup_title: 'No Encryption Keys Found',
    key_setup_desc: 'This device has no encryption keys. Import a backup to access your existing messages, or generate new keys (old messages will be unreadable).',
    key_setup_new: 'Generate New Keys',
    key_setup_new_confirm: 'Warning: old encrypted messages will be unreadable. Continue?',
    enter_backup_password: 'Enter backup password:',
    accent_color: 'Accent color',
    accent_purple: 'Purple',
    accent_blue: 'Blue',
    accent_green: 'Green',
    accent_red: 'Red',
    accent_orange: 'Orange',
    accent_pink: 'Pink',
    accent_teal: 'Teal',
    accent_indigo: 'Indigo',
    sec_privacy: 'Privacy',
    disappearing_messages: 'Disappearing Messages',
    disappearing_off: 'Off',
    disappearing_24h: '24 Hours',
    disappearing_7d: '7 Days',
    disappearing_30d: '30 Days',
    disappearing_timer: 'Disappears in',
    media_decrypt_error: 'Could not decrypt attachment',
    edit_message_prompt: 'Edit message:',
    today: 'Today',
    yesterday: 'Yesterday',
  },
  ru: {
    connected: 'В сети',
    connecting: 'Подключение...',
    disconnected: 'Не в сети',
    reconnecting: 'Переподключение...',
    status_connected: 'Подключено',
    status_disconnected: 'Нет подключения',
    server_unreachable: 'Сервер недоступен. Проверьте подключение.',
    retry: 'Повторить',
    status_connecting: 'Подключение...',
    settings: 'Настройки',
    appearance: 'Внешний вид',
    general: 'Общий чат',
    theme: 'Тема',
    theme_dark: 'Тёмная',
    theme_light: 'Светлая',
    language: 'Язык',
    lang_en: 'English',
    lang_ru: 'Русский',
    notifications: 'Уведомления',
    enable_notifications: 'Включить уведомления',
    sound: 'Звук',
    message_sound: 'Звук сообщений',
    data: 'Данные',
    clear_local_data: 'Очистить локальные данные',
    confirm_clear: 'Очистить',
    confirm_clear_data: 'Очистить все локальные данные?',
    confirm_clear_data_desc: 'Все настройки и ключи шифрования будут удалены. Действие необратимо.',
    cancel: 'Отмена',
    done: 'Готово',
    copy: 'Копировать',
    login: 'Войти',
    register: 'Регистрация',
    nickname: 'Никнейм',
    password: 'Пароль',
    nickname_placeholder: 'Введите никнейм (3-16 символов)',
    password_create: 'Придумайте пароль (8-32 символа, буквы + цифры)',
    password_enter: 'Введите пароль',
    create_account: 'Создать аккаунт',
    sign_in: 'Войти',
    creating_account: 'Создание аккаунта...',
    signing_in: 'Вход...',
    nickname_hint: 'Никнейм: 3-16 символов, только буквы, цифры, _-',
    type_message: 'Введите сообщение...',
    not_connected: 'Нет подключения',
    send_message: 'Отправить сообщение',
    close_settings: 'Закрыть настройки',
    logout: 'Выйти',
    confirm_logout: 'Выйти из аккаунта?',
    confirm_logout_desc: 'Вам придётся войти снова, чтобы продолжить использование.',
    online_users: 'В сети',
    no_messages: 'Пока нет сообщений. Скажите привет!',
    no_dm_messages: 'Пока нет сообщений. Напишите привет!',
    delete: 'Удалить',
    search_messages: 'Поиск сообщений',
    search_messages_hint: 'Поиск в чате...',
    font_size: 'Размер шрифта',
    font_small: 'Маленький',
    font_normal: 'Обычный',
    font_large: 'Большой',
    compact_mode: 'Компактный режим',
    enable_compact: 'Уменьшить отступы',
    about: 'О приложении',
    version: 'Версия',
    contacts: 'Контакты',
    chat: 'Чат',
    back_to_chat: 'Назад к чату',
    dm_with: 'Переписка с',
    no_contacts: 'Пока нет контактов',
    start_dm: 'Написать сообщение',
    search_placeholder: 'Поиск пользователей...',
    search_results: 'Результаты',
    no_results: 'Пользователи не найдены',
    chats: 'Чаты',
    global_chat: 'Глобальный чат',
    global_chat_desc: 'Публичный чат для всех',
    home: 'Главная',
    about_desc: 'Минималистичный мессенджер со сквозным шифрованием. Приватный, разворачивается на вашем сервере, лёгкий и быстрый. Ваши данные остаются у вас.',
    online: 'В сети',
    offline: 'Не в сети',
    sec_appearance: 'Внешний вид',
    sec_text: 'Текст',
    sec_notifications: 'Уведомления',
    sec_account: 'Аккаунт',
    sec_safety: 'Безопасность',
    safety_number: 'Номер безопасности',
    safety_number_desc: 'Сравните этот номер с контактом для подтверждения личности',
    safety_yours: 'Ваш номер безопасности',
    export_keys: 'Экспорт ключей',
    export_keys_desc: 'Скачать зашифрованный бэкап ключей',
    import_keys: 'Импорт ключей',
    import_keys_desc: 'Восстановить ключи из бэкапа',
    screenshot_prot: 'Защита от скриншотов',
    screenshot_prot_desc: 'Блокировать захват экрана',
    sessions: 'Активные сессии',
    sessions_desc: 'Управление подключёнными устройствами',
    sessions_note: 'До 3 активных сессий. Новый вход при достижении лимита отклоняется, пока вы не отзовёте старую сессию.',
    current_session: 'Это устройство',
    editing_message: 'Редактирование сообщения',
    admin_section: 'Модерация',
    admin_reports: 'Жалобы',
    admin_no_reports: 'Жалоб пока нет',
    admin_ban: 'Заблокировать',
    admin_unban: 'Разблокировать',
    admin_ban_nick: 'Блокировка по нику',
    admin_ban_hint: '@никнейм',
    admin_confirm_ban: 'Заблокировать этого пользователя?',
    admin_confirm_unban: 'Разблокировать этого пользователя?',
    admin_blocked: 'Заблокированные пользователи',
    admin_blocked_empty: 'Пока никто не заблокирован',
    admin_unblock: 'Разблокировать',
    admin_channel_general: 'Общий чат',
    admin_channel_dm: 'ЛС',
    blocked_users: 'Заблокированные',
    blocked_hint: '@ник для блокировки',
    block: 'Заблокировать',
    block_confirm: 'Заблокировать этого пользователя? Он больше не сможет вам писать.',
    block_dialog_title: 'Заблокировать пользователя',
    block_dialog_desc: 'Заблокировать этого пользователя? Он больше не сможет писать вам сообщения.',
    blocked_chat_hint: 'Вы заблокировали пользователя. Напишите после разблокировки',
    unblock: 'Разблокировать',
    reply: 'Ответить',
    edit_message: 'Изменить',
    report: 'Пожаловаться',
    report_title: 'Пожаловаться на пользователя',
    report_desc: 'Расскажите, что сделал этот пользователь — модератор рассмотрит жалобу.',
    report_reason_scam: 'Мошенничество',
    report_reason_harassment: 'Оскорбления',
    report_reason_inappropriate: 'Неприемлемый контент',
    report_reason_other: 'Другое',
    report_send: 'Отправить жалобу',
    report_sent: 'Жалоба отправлена. Спасибо, что помогаете делать WhisperNet безопасным.',
    report_hint: 'Кратко опишите проблему (необязательно)',
    revoke: 'Отозвать',
    revoke_all: 'Отозвать все остальные',
    key_exported: 'Бэкап скачан',
    key_imported: 'Ключи восстановлены из бэкапа',
    key_import_err: 'Неверный файл бэкапа или пароль',
    session_revoked: 'Сессия отозвана',
    key_setup_title: 'Ключи шифрования не найдены',
    key_setup_desc: 'На этом устройстве нет ключей шифрования. Импортируйте бэкап для доступа к сообщениям, или сгенерируйте новые ключи (старые сообщения будут недоступны).',
    key_setup_new: 'Сгенерировать новые ключи',
    key_setup_new_confirm: 'Внимание: старые зашифрованные сообщения будут недоступны. Продолжить?',
    enter_backup_password: 'Введите пароль бэкапа:',
    accent_color: 'Цвет акцента',
    accent_purple: 'Фиолетовый',
    accent_blue: 'Синий',
    accent_green: 'Зелёный',
    accent_red: 'Красный',
    accent_orange: 'Оранжевый',
    accent_pink: 'Розовый',
    accent_teal: 'Бирюзовый',
    accent_indigo: 'Индиго',
    sec_privacy: 'Приватность',
    disappearing_messages: 'Исчезающие сообщения',
    disappearing_off: 'Выкл',
    disappearing_24h: '24 Часа',
    disappearing_7d: '7 Дней',
    disappearing_30d: '30 Дней',
    disappearing_timer: 'Исчезнет через',
    media_decrypt_error: 'Не удалось расшифровать вложение',
    edit_message_prompt: 'Редактировать сообщение:',
    today: 'Сегодня',
    yesterday: 'Вчера',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
